version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/postgres?currentSchema=erp_bom
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - CLOUDINARY_URL=cloudinary://387828317835664:pczjanPmGwz5176N9NYuWGJQUaA@dmbcwrpro
      - JWT_SECRET=1234567890123456789012345678901234567890123456789012345678901234
      - JWT_EXPIRATION=86400000
      - PORT=8080
    depends_on:
      - postgres
    networks:
      - erp-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./script/db_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - erp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  erp-network:
    driver: bridge