server:
  port: ${PORT:8080}
  compression:
    enabled: true
  shutdown: graceful

spring:
  application:
    name: erp_bom
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=erp_bom}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

cache:
  type: caffeine
  caffeine:
    spec: maximumSize=100,expireAfterWrite=5m

logging:
  level:
    root: WARN
    com.erp.bom: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

cloudinary:
   url: ${CLOUDINARY_URL:cloudinary://387828317835664:pczjanPmGwz5176N9NYuWGJQUaA@dmbcwrpro}

app:
  jwt:
    secret: ${JWT_SECRET:1234567890123456789012345678901234567890123456789012345678901234}
    expiration: ${JWT_EXPIRATION:86400000}
